<%@ Page Language="C#" AutoEventWireup="True" Inherits="CMS.Employees.Employees_view_purchase_requisition_details" Codebehind="view_purchase_requisition_details.aspx.cs" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" >
<head runat="server">
    <title>Untitled Page</title>
     <link href="includes/css/styles.css" type="text/css" rel="stylesheet" /> 
</head>
<body>
    <form id="form1" runat="server">
     <div id="main_container">

	<!-- start #header -->
	<div id="header">
    
    	<!-- start #logo -->
    	<div id="logo"></div>
        <!-- end #logo -->
        
        <!-- start #login_details -->
        <div id="login_details">
        	<span class="welcome">welcome:</span> <span class="loged_name">
                <asp:Label ID="lblemp" runat="server" ></asp:Label></span>
            <br />
            <span class="date">date: 
                <asp:Label ID="lbldate" runat="server" ></asp:Label></span>  
        
        
        </div>
        <!-- end #login_details -->
        
    </div>
    <!-- end #header -->
    
    <!-- start #header_bg -->
    <div id="header_bg">
    	<a id="A1" href="../Default.aspx" class="logout" runat="server">logout</a>
    </div>
    <!-- end #header_bg -->
    
    <div id="content_holder">
    	<div id="left_navi_holder">
        	<div class="side_navi_gap">&nbsp;</div>
        		<a id="A2" href="#" class="navi_head" runat ="server">Employees</a>
            	<a id="A3" href="view_task.aspx" class="side_navi" runat ="server">view tasks</a>
                <a id="A4" href="create_task .aspx" class="side_navi" runat ="server">create task</a>
                <a id="A5" href="view_task_status.aspx" class="side_navi" runat ="server"> view task status</a> 
                <a id="A6" href="create_daily_report.aspx" class="side_navi" runat ="server">create daily report</a>
                <a id="A7" href="view_daily_report.aspx" class="side_navi" runat ="server">view daily report</a>          
                <a id="A8" href="#" class="navi_head" runat ="server">projects</a>
                <a id="A9" href="view_cars.aspx" class="side_navi" runat ="server">view cars</a>
                <a id="A10" href="view_car_reply.aspx" class="side_navi" runat ="server"> view car reply</a>
                <a id="A11" href="projects_levels_status.aspx" class="side_navi"> project levels status</a>
                <a id="A12" href="view_project_status.aspx" class="side_navi" runat ="server"> view project status</a> 
                <a id="A13" href="view_orders.aspx" class="side_navi" runat ="server"> view orders</a> 
                <a id="A14" href="purchase_requisition.aspx" class="side_navi" runat ="server"> purchase requisition</a>  
                <a id="A15" href="view purchase_requisition.aspx" class="side_navi" runat ="server"> view purchase requisition</a> 
                <a id="A16" href="pretty_expencess.aspx" class="side_navi" runat ="server"> pretty expenses</a>
             <a id="A17" href="view_expences.aspx" class="side_navi">view pretty expenses</a>
                 <a id="A18" href="view_expences_status.aspx" class="side_navi">view expenses status</a></div>
       
        <div id="form_area">
        	<div id="form_head">
            	<div id="left_corner">&nbsp;</div>                
                <div id="right_corner">&nbsp;</div>
                <div id="form_head_text_area">view purchase requisition details</div>
                <asp:Label ID="lblmessage" runat="server"  Visible="False" CssClass="errmsg"></asp:Label>
            </div>
            
            <div id="indent_form_heads">
            	
            	<h6>Requisition generated by:
                    <asp:Label ID="lblempname" runat="server" ></asp:Label></h6>
            	<span class="form_no">Requisition No:
                    <asp:Label ID="lblformno" runat="server" ></asp:Label></span>
                    <span class="form_no">project name:
                    <asp:Label ID="lblprojectid" runat="server" ></asp:Label></span>  
                    <asp:Label ID="lblpuchaseorder_id" runat="server" Text=""></asp:Label>&nbsp;&nbsp;&nbsp;
                    <asp:Label ID="lblrequisition_id" runat="server" Text=""></asp:Label>
                    <span  class ="requistion_id"> 
                    <asp:Label ID="lblaccepted" runat="server" Text="Accepted By :" Visible="false"></asp:Label> <asp:Label ID="lblstatuschangedbyemp" runat="server" Text="" Visible="false"></asp:Label></span>
                    <span class="form_date">Requisition Generated Date:<asp:Label ID="lblcreatedate" runat="server" ></asp:Label></span>
                      
            </div>
            	 
            <div id="form">
            <table width="100%" border="0" cellspacing="0" cellpadding="0">
              
              <tr>
                <td valign="top" class="grid_content_indent_1"  Width ="100%" colspan="2">
                
                    <asp:GridView ID="GridView1" runat="server" Width ="100%" AutoGenerateColumns ="false"  DataKeyNames="requisition_detail_id" CssClass="grid_content_1"  PageSize="2"    >
                   <Columns >
                  <%--  <asp:BoundField HeaderText ="Requisition detail id" DataField ="requisition_detail_id" >
                       <HeaderStyle CssClass="grid_head" />
                   </asp:BoundField>--%>
                   <asp:BoundField HeaderText ="Item name" DataField ="material_name" >
                       <HeaderStyle CssClass="grid_head" />
                   </asp:BoundField>
                   <asp:BoundField HeaderText ="Description" DataField ="description" >
                       <HeaderStyle CssClass="grid_head" />
                   </asp:BoundField>
                   <asp:BoundField HeaderText ="Quantity" DataField ="quantity" >
                       <HeaderStyle CssClass="grid_head" />
                   </asp:BoundField>
                   </Columns>
                   </asp:GridView> 
                    </td> 
                    </tr>
                  <tr>
                   <td colspan="2">
                      
                       
                       
                       <asp:RadioButtonList ID="rbtn" runat="server" AutoPostBack="false">
                       </asp:RadioButtonList>
                   </td>
                   </tr>
                   <tr>
                  
                      <td  align="center"  colspan="2">
                        <asp:Button ID="btnsubmit" runat="server" Text="submit"  CssClass="btn" OnClick="btnsubmit_Click1"  />
                         <asp:Button ID="btnback" runat="server" Text="back"  CssClass="btn" OnClick="btnback_Click"   />
                         <asp:Label ID="lblerr_msg" runat="server"  CssClass ="errmsg" Visible="False"></asp:Label>
                        </td>
                  </tr>
                 
                </table>
          </div>
        </div>
       
    </div>
    
  <div id="footer">
    </div>	
    </div>
    </form>
</body>
</html>
